name: nightly-preds
on:
  schedule:
    - cron: "15 3 * * *"   # 03:15 UTC daily
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        env:
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}
        run: python elo_logit_pipeline.py
      - name: Commit artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add predictions_*.csv parlay_suggestion.csv || true
          git commit -m "Nightly preds $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
